apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# oc login <cluster> && oc project jet-surrogate && oc apply -k deploy/paas
resources:
  - configmap.yaml
  - pvc.yaml
  - deployment-web.yaml
  - deployment-worker.yaml
  - service.yaml
  - route.yaml
  - cronjob-cleanup.yaml
commonLabels:
  app: jet-surrogate
images:
  - name: ghcr.io/jburzy/jet-surrogate
    newTag: latest
